### ISSUE TITLE
"Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by ajbowler** [hughsk/komponist#8]
I'm currently working on a class project dealing with MPD and I'm attempting to use Komponist. I'm running into an issue and I was wondering if you could help me solve this problem since you developed Komponist.

Here I have the following code that just attempts to create a connection to my MPD server.

```
var komponist = require('komponist');

var client = komponist.createConnection(6600, 'localhost', function() {
  console.log('Connected!');
});
```

However, when I try to execute this code the Chrome debugger's returning "Cannot read property 'apply' of undefined " and it's pointing to this:

```
MPDClient.prototype.connect = function() {
    var returnVal = MPDClient.super_.prototype.connect.apply(this, arguments);
    this.write = MPDClient.prototype.write;
    return returnVal;
}
```

At first I thought it was because MPD simply wasn't running or there was a connection issue but my MPD server is running on localhost:6600 and I can connect to it just fine from another third party client, so I'm wondering if I'm missing a library or some other dev dependencies to use komponist. I'm not familiar with the "super_" notation.

If you have any ideas as to what's causing this issue I'd be eternally grateful. If possible, I need to know this ASAP for project deadlines. Thanks so much!

**Comment by bananushka** [comment]
Well, komponist requires node.js libs in order to function, so it's
strictly a server-side module. If you want to use it in the browser, I
suggest writing a server in node that speaks to the client through socket.io
or something similar.
